name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: 
     - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!"
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      # - name: Deploy to Firebase
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASTANGAYOGASHALA_B9709 }}'
      #     channelId: live
      #     projectId: astangayogashala-b9709
      #     entryPoint: "./firebase_yogawebsite"
